# Generated by Django 4.0.4 on 2022-05-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'visa'), ('rupay', 'rupay'), ('master card', 'master card')], max_length=15)),
                ('card_number', models.BigIntegerField()),
                ('cvv_number', models.IntegerField()),
                ('expires_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='user.user')),
            ],
        ),
    ]
