# Generated by Django 4.0.4 on 2022-05-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('plan_type', models.CharField(choices=[('1', 'Monthly'), ('2', 'Quarterly'), ('3', 'Annually')], max_length=1)),
                ('amount', models.IntegerField(default=None)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='service.service')),
            ],
        ),
    ]
